name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-binaries:
    name: Build binaries
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: '--snapshot --rm-dist --timeout 60m' # will not release
    secrets: inherit

  upload-binaries:
    name: Upload binaries
    needs: build-binaries # run this job after 'build-binaries' job completes
    runs-on: ubuntu-latest
    steps:
      - name: Restore Trivy plugin attest binaries from cache
        uses: actions/cache@v3.0.9
        with:
          path: dist/
          key: ${{ runner.os }}-bins-${{github.workflow}}-${{github.sha}}

        # Upload artifacts
      - name: Upload artifacts (trivy_plugin_attest_Linux-64bit)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_plugin_attest_Linux-64bit
          path: dist/trivy_plugin_attest_*_Linux-64bit.tar.gz
          if-no-files-found: error

      - name: Upload artifacts (trivy_plugin_attest_Linux-ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_plugin_attest_Linux-ARM64
          path: dist/trivy_plugin_attest_*_Linux-ARM64.tar.gz
          if-no-files-found: error

      - name: Upload artifacts (trivy_plugin_attest_macOS-64bit)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_plugin_attest_macOS-64bit
          path: dist/trivy_plugin_attest_*_macOS-64bit.tar.gz
          if-no-files-found: error

      - name: Upload artifacts (trivy_plugin_attest_macOS-ARM64)
        uses: actions/upload-artifact@v3
        with:
          name: trivy_plugin_attest_macOS-ARM64
          path: dist/trivy_plugin_attest_*_macOS-ARM64.tar.gz
          if-no-files-found: error
